# Generated by Django 4.2.13 on 2024-05-28 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_title', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('category', models.CharField(choices=[('10% finished', '10% finished'), ('30% finished', '30% finished'), ('50% finished', '50% finished'), ('75% finished', '75% finished'), ('100% finished', '100% finished')], max_length=50)),
                ('status', models.IntegerField(default=0)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management_app.schemes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management_app.people')),
            ],
        ),
    ]
