# Generated by Django 4.2.13 on 2024-05-28 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0002_work'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='category',
            new_name='complete',
        ),
    ]
