# Generated by Django 4.2.13 on 2024-05-30 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0004_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='complete',
            field=models.CharField(choices=[('work started', 'work started'), ('10% finished', '10% finished'), ('30% finished', '30% finished'), ('50% finished', '50% finished'), ('75% finished', '75% finished'), ('100% finished', '100% finished')], max_length=50),
        ),
    ]
